### ISSUE TITLE
Support for Laravel 6

### ISSUE THREAD

**Issue by ghost** [pepijnolivier/Eloquent-Model-Generator#18]
Will this work with a 6 project?

**Comment by pepijnolivier** [comment]
No, this repo has been mostly abandoned, but I might just find time to release a fresh version some weeks in the future.
You should probably check out the forks for now though, or use a similar package.

**Comment by pepijnolivier** [comment]
FYI, Laravel 6 will not be supported, but I'm working on a new release, to be finished soon. 
It targets Laravel 8+ and PHP 8.1.
