### ISSUE TITLE
only specific tables won't work

### ISSUE THREAD

**Issue by Jurek-Raben** [pepijnolivier/Eloquent-Model-Generator#3]
If I use it with the following command (taken from help: "models:generate [options] [--] [<tables>]"):
 php artisan models:generate table1,table2,table3...

it still will generate all tables from database.

Also this still will generate all tables:
php artisan models:generate --tables=table1,table2,table3...

**Comment by pepijnolivier** [comment]
@JurekRaben I will take a look at this later this week!

**Comment by pepijnolivier** [comment]
@JurekRaben 

Fixed in https://github.com/pepijnolivier/Eloquent-Model-Generator/commit/e86823900bd1feabdcfcfbf4bbee3ac924d36146

Will get merged in v1.0.1 later today. I'm also updating the readme.
