### ISSUE TITLE
Add to Packagist

### ISSUE THREAD

**Issue by mstaack** [pepijnolivier/Eloquent-Model-Generator#7]
hey @pepijnolivier 

we should consider registering this generator to packagist.

and begin with tagging releases.

Would help!

Cheers Max

**Comment by pepijnolivier** [comment]
Hi @mstaack 

This package is already available on packagist, see
https://packagist.org/packages/user11001/eloquent-model-generator

Tagging releases would be the next thing to do, but I've recently had contact with the author of https://github.com/mitulgolakiya/laravel-api-generator who has a package that will generate not only models, but also CRUD views, repositories and more.

This guy is now in the process of making a new version of his package (hasn't yet published to github), but I'm planning to merge model generator functionality in his package soon.

**Comment by mstaack** [comment]
sounds awesome
