### ISSUE TITLE
Namespace not flexible

### ISSUE THREAD

**Issue by tomsowerby** [pepijnolivier/Eloquent-Model-Generator#8]
Hello,
I've run across a slight issue when using your otherwise very useful library.
When a user can specify the path for the location of the files to be created, using the APP_NAME or default App\Models namespace doesn't seem flexible enough to comply with PSR-4.

Could namespace be added as an option, so that a user can explicitly specify the model namespace and path when creating them?

Thanks.

**Comment by pepijnolivier** [comment]
@tomsowerby

Fixed in https://github.com/pepijnolivier/Eloquent-Model-Generator/commit/6e48db7bae33210ea92cea08a2a16f415c630e94

I am committing a few items right now, and will release this under `v1.0.1` later today - sorry for the late response. I'm also updating the readme.
